// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  image_gallery: dynamic(() => import("./ImageGallery")),
  next_article: dynamic(() => import("./NextArticle")),
  rich_text: dynamic(() => import("./RichText")),
  video: dynamic(() => import("./Video")),
};
